import type { Enums } from "src/database.types";

export const BOOK_GENRE_OPTIONS: Enums<'book_genre'>[] = [
    'Fiction',
    'Non-fiction',
    'Mystery',
    'Thriller',
    'Romance',
    'Science Fiction',
    'Fantasy',
    'Horror',
    'Historical Fiction',
    'Biography',
    'Autobiography',
    'Memoir',
    'Self-help',
    'Business',
    'Philosophy',
    'Poetry',
    'Drama',
    'Adventure',
    'Young Adult',
    `Children's`,
    'Graphic Novel',
    'Crime',
    'Dystopian',
    'Humor',
    'Travel',
    'Cookbook',
    'Art',
    'Science',
    'Technology',
    'History',
  ];